### ISSUE TITLE
Translation of SOS description in Services

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/starterkit#119]
the description of SOS services in the page about_service is not translated in English

**Comment by wlorenzetti** [comment]
@oggioniale every service are only in Italian, look at http://demo2.get-it.it/about_services/.
Please send me translation.

**Comment by wlorenzetti** [comment]
@oggioniale can you send me the translations for other sections services? WMS WFS CSW...

**Comment by oggioniale** [comment]
**for WMS:**
[Web Map Service (WMS)](https://en.wikipedia.org/wiki/Web_Map_Service) is a technical specification defined by the [Open Geospatial Consortium (OGC)](https://en.wikipedia.org/wiki/Open_Geospatial_Consortium), which dynamically produces spatially referenced data maps from geographic information. This international standard defines a "map" as a representation of geographical information by returning a digital image suitable for display on a web browser.

Generally a WMS is not directly invoked; client applications such as GIS-Desktop or WEB-GIS are used that provide the user with interactive controls.

**for WFS:**
The [Open Geospatial Consortium (OGC)](https://en.wikipedia.org/wiki/Open_Geospatial_Consortium) [Web Feature Service Standard Interface (WFS)](https://en.wikipedia.org/wiki/Web_Feature_Service) allows a client to request and import geographic objects through the Web, using platform-independent calls.

Generally a WFS is not directly invoked; client applications such as GIS-Desktop or WEB-GIS are used that provide the user with interactive controls.

**for WCS:**
The [Open Geospatial Consortium (OGC)](https://en.wikipedia.org/wiki/Open_Geospatial_Consortium) [Web Coverage Service (WCS)](https://en.wikipedia.org/wiki/Web_Coverage_Service) standard defines a standard interface and operations that allow interoperable access to geographical coverages. The term "grid coverage" typically refers to content such as satellite images, digital aerial photos, digital elevation data, and other phenomena represented by values at each measurement point.

Generally a WCS is not directly invoked; client applications such as GIS-Desktop or WEB-GIS are used that provide the user with interactive controls.

**for CSW:**
The [Open Geospatial Consortium (OGC)](https://en.wikipedia.org/wiki/Open_Geospatial_Consortium) [Catalog Service for the Web (CSW)](https://en.wikipedia.org/wiki/Catalog_Service_for_the_Web) standard defines an interface for search, navigation and querying metadata on data, services, and other potential resources. It refers to the Internet-based publication of information on space applications, geo-services and spatial data (metadata) in a spatial data infrastructure.

**for WMTS:**
The [Open Geospatial Consortium (OGC)](https://en.wikipedia.org/wiki/Open_Geospatial_Consortium) [Web Map Tile Service (WMTS)](https://en.wikipedia.org/wiki/Web_Map_Tile_Service) standard provides international specifications for serving geographic data on the web through "cached image tiles".
