### ISSUE TITLE
Editing documenti: non viene visualizzato il campo "punto di contatto" 

### ISSUE THREAD

**Issue by ABasoni** [SP7-Ritmare/starterkit#12]
Problema evidenziato durante il test di http://sk.fg.ismar.cnr.it/ da G. Pazienza. Compare il campo "owner" con l'utente geonode che ha inserito il documento, ma non viene visualizzato il campo "punto di contatto" anche se questo viene compilato in editing. Spesso questo campo è più importante dell'owner di geonode, come nel caso di Lesina in cui i documenti sono caricati da Gianfranco ma spesso sono articoli di qualcun altro del suo istituto. Sarebbe da visualizzarli entrambi

**Comment by menegon** [comment]
Risolto con aggiornamento del nodo
