### ISSUE TITLE
Insert observations for registered sensor: Not authorized for transactional operations!

### ISSUE THREAD

**Issue by wlorenzetti** [SP7-Ritmare/starterkit#130]
During the new observations saving call to SOS service return a 'Not authorized for transactional operations!'

POST: http://demo0.get-it.it/observations/sos/pox

<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>Not authorized for transactional operations!</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>

**Comment by francbartoli** [comment]
@wlorenzetti is it still happening?
