### ISSUE TITLE
edit layer

### ISSUE THREAD

**Issue by simonelanucara** [SP7-Ritmare/starterkit#144]
when editing an existing vector layer with edit layer command the result is not saved, but gives an error, see image

![immagine](https://user-images.githubusercontent.com/7208995/42032849-31c4dad0-7adb-11e8-9478-4f750661579e.jpg)

**Comment by francbartoli** [comment]
@simonelanucara I haven't been able to reproduce it till now. Could you please try again with the latest #145 ?
