### ISSUE TITLE
Upload large layer

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/starterkit#149]
When uploading a vector (shp) large file response error
![screen shot 2018-07-04 at 17 31 36](https://user-images.githubusercontent.com/1393893/42285629-7ebbdb16-7fb0-11e8-8f38-a6855bca5715.png)

**Comment by francbartoli** [comment]
The image of nginx has been updated. @oggioniale can you please try again? Remember to remove the previous nginx image before running the docker-compose up
