### ISSUE TITLE
Esplora Layer: problemi nella visualizzazione dei file (tiff) caricati

### ISSUE THREAD

**Issue by ABasoni** [SP7-Ritmare/starterkit#15]
Problema emerso durante il test di http://skmi.irea.cnr.it/maps/ 
Venivano visualizzati solo alcuni tiff, variabili in modo discontinuo con i livelli di zoom, magari è solo un problema di cache?

**Comment by menegon** [comment]
#ABasoni Questo problema esiste ancora ? puoi inserire un url specifico?
