### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by lukasalexanderweber** [SP7-Ritmare/starterkit#208]
Hello

I'm currently searching for a web interface and wanted to try your demo I've found on https://www.osgeo.org/projects/get-it/ -> http://demo2.get-it.it/

Would love to check into it, however the server is probably down.

**Comment by oggioniale** [comment]
Hi Lukas,
in this days we working to the update to the GET-IT with the last version of GeoNode.
The demo is down. We hope to finish the implementation and internal test soon.

I will write you a soon of possible.

Regards

Alessandro

**Comment by lukasalexanderweber** [comment]
Hi Alessandro,
Great! thank you for the quick response!
Cheers Lukas

**Comment by oggioniale** [comment]
Dear lukasalexanderweber,
now a stable version has been released.
We have installede a new demo version in [http://demo0.get-it.it](http://demo0.get-it.it)
Please let me know

Alessandro

**Comment by lukasalexanderweber** [comment]
Perfekt, thank you!
