### ISSUE TITLE
Help EDI - sensor metadata: improve description of fields

### ISSUE THREAD

**Issue by ABasoni** [SP7-Ritmare/starterkit#26]
issue emerged during the test of La Spezia SK (Chiappini) - EDI Sensor metadata

EDI sensor metadata help, at page: http://sp7.irea.cnr.it/wiki/index.php/Help_Editing_Metadati_dei_Sensori
should be improved to avoid misunderstanding of items to be filled in

**Comment by pepemonica** [comment]
Help texts have been amended and improved
