### ISSUE TITLE
manage style error

### ISSUE THREAD

**Issue by andvianello** [SP7-Ritmare/starterkit#35]
Partendo dalla pagina: http://geosk.ve.ismar.cnr.it/layers/geonode:istituti
e accendendo al tool "manage style" si ottiene la seguente risposta:
IntegrityError at /layers/geonode:istituti/style/manage

**Comment by menegon** [comment]
Sembra risolto

**Comment by andvianello** [comment]
L'errore persiste solo su questo layer: http://geosk.ve.ismar.cnr.it/layers/geonode:istituti

Non si riesce a modificare lo stile partendo dal tool "layer style".

**Comment by menegon** [comment]
L'errore non si verifica se prima di modificare le "rule"/"regole" si seleziona lo stile con il "menu a tendina".
La soluzione definitiva è apparentemente complessa ed implicata la modifica di alcune librerie esterne. 
Probabilmente si può ovviare segnalando la soluzione nella documentazione.
Sposterei poi la soluzione definitiva alla 2.0.
