### ISSUE TITLE
sostituzione layer

### ISSUE THREAD

**Issue by andvianello** [SP7-Ritmare/starterkit#36]
La sostituzione di un layer (aggiornamento) con uno esistente mantenendo lo stesso metadato, va a buon fine solamente se il nuovo layer presenta gli stessi attributi di quello precedente.
Inoltre se la sostituzione non va a buon fine, spesso geonode manda un messaggio di "layer caricato correttamente" anche se in realtà il layer non viene sostituito provocando equivoci.

**Comment by menegon** [comment]
Ho fatto qualche prova modificando alcuni valori in alcune colonne già esistenti e aggiungendo una colonna nuova.
Dopo l'upload, vengono modificati i valori nelle colonne già esistenti, mentre vengono ignorate le nuove colonne. 
Bisognerebbe fare qualche test eliminando colonne ecc.
In ogni caso penso che la soluzione migliore sia quella di aggiungere un warning dicendo che la struttura delle colonne deve essere la stessa.
