### ISSUE TITLE
Suggestion: Report also the temporal extent in the infos of a layer

### ISSUE THREAD

**Issue by lbusett** [SP7-Ritmare/starterkit#40]
In the "details" page that appears after selecting a layer, I'd suggest to report not only the publication date, but also the temporal extent of the layer.

**Comment by menegon** [comment]
Added temporal extent on "details page". Limitation: is reported only the first temporal extent

**Comment by menegon** [comment]
Added temporal extent on "details page". Limitation: is reported only the first temporal extent.
