### ISSUE TITLE
problemi server

### ISSUE THREAD

**Issue by andvianello** [SP7-Ritmare/starterkit#46]
Nello starterkit Lesina non si salvano correttamente le modifiche ai metadati dei layer.
C'è differenza tra la scheda editing e quelladi visualizzazione. Il titolo modificato in editing  non viene visualizzato nella visualizzazione:

http://sk.fg.ismar.cnr.it/layers/geonode:siti_osservativi_fissi_nel_golfo_di_manfredonia_te

**Comment by menegon** [comment]
La versione 1.2.7 conteneva un bug. Risolto aggiornando alla 1.2.8.
