### ISSUE TITLE
"Register" button for saving layer metadata

### ISSUE THREAD

**Issue by alesarrett** [SP7-Ritmare/starterkit#49]
When a user edits metadata for a layer, to save the modified metadata he has to click on the "Register" button. It probably comes from the registration of sensors, but in case of metadata for layers (or views) it would be better to change the label of the button from "Register" to "Save" or "Update".

**Comment by andvianello** [comment]
Il problema è stato risolto solo per i layer nuovi, mentre persiste per quello vecchi
