### ISSUE TITLE
Keywords on layer not correctly updated

### ISSUE THREAD

**Issue by alesarrett** [SP7-Ritmare/starterkit#51]
It seems that some issues are present when adding keywords for a layer.
Tested with the layer http://demo1.get-it.it/layers/geonode:bathymetry_venice
In the ediclient, while inserting keywords, everything seems to be fine. But when a user re-open the metadata in editing, some issues arise:
- the INSPIRE keyword is not present (Elevation was inserted)
- in some of the keywords added from controlled vocabularies (not the first, in my case) it seems that something is still running, being present an icon on the second and third keyword.
- the last keyword has been added but nothing is visibile (it was "Lagoons" from GCMD)

See image below):
![selection_036](https://cloud.githubusercontent.com/assets/1692316/7785999/c8db447a-01af-11e5-9e39-152791d2ac9b.png)

Then, in the layer info page all the three keywords from controlled vocabularies are present (not the INSPIRE one) plus another one: ERMES (see image below):
![selection_037](https://cloud.githubusercontent.com/assets/1692316/7785989/3ebc32b8-01af-11e5-98e0-1a810e8445ad.png)

**Comment by menegon** [comment]
@fabiopavesi  could you have a look at this?

**Comment by fabiopavesi** [comment]
I am
