### ISSUE TITLE
Metadata editing on last GET-IT realese

### ISSUE THREAD

**Issue by IAMCOristano** [SP7-Ritmare/starterkit#56]
I found some problems in metadata edit procedure after the upgrade from "Starterkit" to "Get/it". It is not possible to edit metadata already loaded on starterkit previous release; metadata are stored and visible in the layer description below, but going on "edit metadata (inspire)"  the new window of metadata compilation appears empty. 
Also when i go on "edit metadata (insipre)", a windows appeares with "save or upload" metadata file option on the left side, but only for less than a second, it is possible to verify this option?   
Thanks in advance
Alessandro

IAMC ORISTANO
sk.oristano.iamc.cnr.it

**Comment by menegon** [comment]
Fixed on 1.2.14

**Comment by IAMCOristano** [comment]
Perfect! :dancer:
