### ISSUE TITLE
error while changing password

### ISSUE THREAD

**Issue by ptagliolato** [SP7-Ritmare/starterkit#58]
While changing password for user starterkit I got the following error (but password change succeded):
SMTPRecipientsRefused at /account/password/

{u'help.skritmare@irea.cnr.it': (553, "sorry, that domain isn't in my list of allowed rcpthosts (#5.7.1)")}

Request Method: 	POST
Request URL: 	------------
Django Version: 	1.5.5
Exception Type: 	SMTPRecipientsRefused
Exception Value: 	

{u'help.skritmare@irea.cnr.it': (553, "sorry, that domain isn't in my list of allowed rcpthosts (#5.7.1)")}

Exception Location: 	/usr/lib/python2.7/smtplib.py in sendmail, line 740
Python Executable: 	/usr/bin/python
Python Version: 	2.7.3
Python Path: 	

['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL',
 '/usr/lib/pymodules/python2.7']

Server time: 	lun, 21 Set 2015 05:28:29 -0500

**Comment by andvianello** [comment]
This problem was resolved.
