### ISSUE TITLE
MapQuest base layers no longer available

### ISSUE THREAD

**Issue by lbusett** [SP7-Ritmare/starterkit#72]
Hi all, 

    just to update you on the fact that the MapQuest openstreetmap and MapQuest Imagery basemaps to which getIT views default are no longer distributed freely, so they don't work anymore. It could be good to change the default basemap, maybe. 

ciao, 
Lorenzo
 
![plotimage1](https://cloud.githubusercontent.com/assets/4480397/19271368/b4ec4bcc-8fc4-11e6-805a-fda13c7d0c9c.png)

**Comment by menegon** [comment]
Added documentation to deal with MapQuest issue
http://getit.readthedocs.io/en/latest/tutorials/admin/mapquest_maps_issue.html
