### ISSUE TITLE
GET-IT geoserver link

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/starterkit#83]
In Admin user menu geoserver field is linked to localhost

**Comment by francbartoli** [comment]
@oggioniale This is just a matter of configuration within settings/local_settings

**Comment by simonelanucara** [comment]
The issue still persist, now is linked to external ip address, it should be changed to domain name

**Comment by francbartoli** [comment]
@simonelanucara that change can be done in the django.env and geoserver.env files by setting these variables:

GEONODE_LB_IP=example.com
GEONODE_LB_PORT=80
