### ISSUE TITLE
Register new sensor page

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/starterkit#95]
Register new sensor button return this error:

Request Method: | GET
-- | --
http://demo1.get-it.it/static/EDI-NG_client/SensorML101_forRITMARE.html?parameters=%7B%22user_username%22%3A%22admin%22%2C%22user_email%22%3A%22ad%40m.in%22%2C%22user_profile_organization%22%3A%22%22%2C%22user_profile_email%22%3A%22%22%2C%22user_groups%22%3A%22anonymous%22%7D
django.contrib.staticfiles.views.serve

**Comment by wlorenzetti** [comment]
This it would be fix by my last pull request, with new docker-compose up --build it would work.

**Comment by francbartoli** [comment]
@wlorenzetti I rebuild the django image from scratch and it doesn't still work. I have the impression that such compilation went right during the dockerfile build but it is not maintained till the process execution. We can try to move that part to the entrypoint before the server is started

**Comment by wlorenzetti** [comment]
Add EDI-NG_client code to starterkit core.
